### ISSUE TITLE
uppercase, snakecase & co

### ISSUE THREAD

**Issue by Stargateur** [rodrimati1992/const_format_crates#18]
I need these feature to make a more structured command line options handling:

1. add a format flag or something to make thing upper case ?
2. add way to format using snakecase, kebabcase (and possibly uppercase variant) ?

Do you thing it's in the scope of this crate ? (similar to https://docs.rs/const-str/0.1.4/const_str/ but this crate doesn't work with anything that is not a literal)

**Comment by rodrimati1992** [comment]
Just looking at how complex `str::to_lowercase` is, and how that would get more complex when translated to const-compatible code, I'm not gonna implement it for arbitrary unicode.

I could write a `change_ascii_case` macro to change the casing style of `&str`s based on a `CaseStyle` enum,
in pseudocode: `const fn change_ascii_case(&'static str, CaseStyle) -> &'static str`.

**Comment by Stargateur** [comment]
ascii is totally by for my use case, but that would be nice to have a utf8 one, I didn't yet used a lot of const fn in rust, but I through this crate was using a proc macro, so I didn't think it was a problem.

**Comment by rodrimati1992** [comment]
Proc macros have to emit `const` code to be able to process `const` arguments. If the argument was a literal then you *could* just use the `str::to_uppercase` method from within the proc macro to uppercase it, like `const_str` does.

**Comment by rodrimati1992** [comment]
I started working on the `map_ascii_case` macro in the [case_conv](https://github.com/rodrimati1992/const_format_crates/tree/case_conv) branch, I already implemented lowercase and uppercase conversion.

**Comment by rodrimati1992** [comment]
Done, I've implemented the [`map_ascii_case`](https://docs.rs/const_format/0.2.15/const_format/macro.map_ascii_case.html) macro for the 0.2.15 release
