### ISSUE TITLE
license file not included in crate

### ISSUE THREAD

**Issue by carlwgeorge** [rodrimati1992/const_format_crates#24]
The latest crate uploaded to crates.io (currently 0.2.14) does not include the license file.  The license requires it be included in any source distribution.

> 3. This notice may not be removed or altered from any source distribution.

Please upload a newer crate that includes the license.

**Comment by rodrimati1992** [comment]
Thanks for creating this issue, I had the license in the list of files to include, but I wasn't aware that [cargo doesn't upload files in parent directories](https://github.com/rust-lang/cargo/issues/9667).

Fixed this in 0.2.20 a few minutes ago.
