### ISSUE TITLE
`formatcp` fails `clippy::double_parens` lint.

### ISSUE THREAD

**Issue by olson-sean-k** [rodrimati1992/const_format_crates#38]
It appears that a somewhat recent release within the `^0.2.0` version specification has introduced a failure against [the `clippy::double_parens` lint](https://rust-lang.github.io/rust-clippy/master/#double_parens) in the `formatcp` macro. I've noticed this failure in CI runs but not in local builds until running `cargo update` to update the local lock file (and the crate I'm developing depends on `^0.2.0`).

[Here's an example](https://github.com/olson-sean-k/wax/runs/6868114501?check_suite_focus=true#step:4:116) of such a failed CI run. The `sepexpr` and `nsepexpr` macros cited in the errors invoke `formatcp` and `rustc` notes that the errors originate there.

`clippy::double_parens` is part of the standard `clippy::all` group and is not considered pedantic.

**Comment by rodrimati1992** [comment]
AFAICT, this is caused by clippy not taking into account macros when detecting double parentheses. 

For example, this code causes that warning (despite not containing any visible double parentheses):
```rust
macro_rules! foo {
    () => {(100)}
}

fn main(){
    (foo!());
}
```

**Comment by rodrimati1992** [comment]
Hmm, I'm can't reproducing this with `formatcp`. Do you have a self-contained snippet that uses `formatcp` which reproduces the lint triggering?

**Comment by olson-sean-k** [comment]
Sorry for not getting back to this sooner. Thanks for taking a look (and for the fix)!
