### ISSUE TITLE
[Feature request] Add equivalents of `include_str!`, `include_bytes!`

### ISSUE THREAD

**Issue by rben01** [rodrimati1992/const_format_crates#40]
I would like to be able to use this crate to construct compile-time paths to pass to the stdlib `include_str!` and `include_bytes!` macros. Unfortunately these two macros only accept string literals, not arbitrary const strings (which seems like a silly limitation, but that's how it is). It would be great if `const_format` had equivalent macros which could take a const str and turn it into compile-time `&str` or `&[u8]`, so that I could do e.g., `include_const_str!(concatcp!(env("CARGO_MANIFEST_DIR"), MY_PATH))`.

**Comment by rodrimati1992** [comment]
The result of evaluating a constant can't be turned into a literal, so there's no way to do a const-evaluation equivalent of  the `std::include_*` macros.
