### ISSUE TITLE
why there is no `str_split!(string, needle)` macro ?

### ISSUE THREAD

**Issue by alexzanderr** [rodrimati1992/const_format_crates#41]
i've seen a lot useful macros for const string operations

like [`str_index`](https://docs.rs/const_format/latest/const_format/macro.str_index.html)

but i really need a str_split macro, why there is no such macro ?

and also there is none in the `const_str` crate.

thanks in advance.

**Comment by rodrimati1992** [comment]
This is definitely possible, but it requires the [`const_slice_from_raw_parts`](https://github.com/rust-lang/rust/issues/67456) unstable feature that should stabilize soon (without it `str_split` would have quadratically slow performance relative to the length of the string).
I just started working on this, it'll be in the next patch release (assuming that there's no sudden need for a patch before this is ready)

**Comment by alexzanderr** [comment]
thanks for response.

nice. 

i wish you success!

**Comment by rodrimati1992** [comment]
With the 0.2.26 release, which includes the [`str_split`](https://docs.rs/const_format/0.2.26/const_format/macro.str_split.html) macro, this issue can be closed.
