### ISSUE TITLE
The `{:x}` not in par with std, `{:X}` missing

### ISSUE THREAD

**Issue by michalfita** [rodrimati1992/const_format_crates#42]
My tests failed miserably in result of that problem. The standard library `format!()` macro formats hexadecimal numbers capitalized if `{:X}` is used, but in lower characters if `{:x}` is used.

Thanks for great create, but please fix this.

**Comment by rodrimati1992** [comment]
Alright, I'll work on this now, I'll probably be finished tomorrow.

**Comment by rodrimati1992** [comment]
Turns out that it's today, not tomorrow: https://docs.rs/const_format/0.2.30/const_format/macro.formatcp.html#syntax

**Comment by michalfita** [comment]
🙏🏼 Thank you very much.
