### ISSUE TITLE
Some constants are shown in the documentation

### ISSUE THREAD

**Issue by bestgopher** [rodrimati1992/const_format_crates#50]
When I use the crate, run `cargo doc --open`, many unknown constants are shown in browser.
```rust
const A: &str = const_format::formatcp!("{}", "a");
const B: &str = const_format::formatcp!("{}", "b");
const C: &str = const_format::formatcp!("{}", "C");
fn main() {}
```
<img width="449" alt="image" src="https://github.com/rodrimati1992/const_format_crates/assets/36840497/ca448cb4-af6f-4285-a295-ed3374ff4510">

**Comment by rodrimati1992** [comment]
[The PR to fix](https://github.com/rodrimati1992/const_format_crates/pull/51) has been merged, and the fix is in the [0.2.31 release](https://crates.io/crates/const_format).
