### ISSUE TITLE
`concatcp` and `formatcp` cannot use args of a `const fn`

### ISSUE THREAD

**Issue by Einliterflasche** [rodrimati1992/const_format_crates#53]
Hi,

first of all, thank you for the crate :).

I tried to use the following code:

```rust
const fn foo(left: &'static str, right: &'static str) -> &'static str {
    // Errors occur here
    concatcp!(left, right)
}
```

which should work given that `left` and `right` are both `'static` and that the following code also works:

```rust
const A: &str = "A";
const B: &str = "B";
const C: &str = {
    concatcp!(A, B)
}
```

The first one, however, results in these errors (note that I tried `formatcp` here, but it's the same story):

```
error[E0435]: attempt to use a non-constant value in a constant
  --> src/main.rs:16:23
   |
16 |     formatcp!("{}{}", left, right)
   |     ------------------^^^^-------- this would need to be a `let`
```

```
error[E0435]: attempt to use a non-constant value in a constant
  --> src/main.rs:16:29
   |
16 |     formatcp!("{}{}", left, right)
   |     ------------------------^^^^^- this would need to be a `let`
```

```
note: erroneous constant used
  --> src/main.rs:16:5
   |
16 |     formatcp!("{}{}", left, right)
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this note originates in the macro `$crate::pmr::__formatcp_impl` which comes from the expansion of the macro `formatcp` (in Nightly builds, run with -Z macro-backtrace for more info)
```

```
note: erroneous constant used
  --> src/main.rs:16:5
   |
16 |     formatcp!("{}{}", left, right)
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this note originates in the macro `__cf_osRcTFl4A::__concatcp_inner` which comes from the expansion of the macro `formatcp` (in Nightly builds, run with -Z macro-backtrace for more info)
```

My best guess is that this is not possible until inline const is a thing, but I wanted to bring this to your attention anyway.

Cheers

**Comment by rodrimati1992** [comment]
The compiler is correct here, function parameters can't be used as arguments for `concatcp` or `formatcp`, only constant expressions can be.

There's two issues here:
-  The code inside `const` functions can't do any more than what non-`const` functions can do.
- `&'static str` parameters are not a guarantee that the parameter is a `&str` constant, since the string can be created at runtime.

# Creating a `&'static str` at runtime

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=d5aa02cc54244ecc136416145905821d
```rust
use std::sync::OnceLock;

static S: OnceLock<String> = OnceLock::new();

const fn foo(_: &'static str) {}

fn main(){
    let val = 3;
    let string: &'static str = S.get_or_init(|| format!("{val:#x}"));
    foo(string);
}
```
