### ISSUE TITLE
Enum `__Foo_osRcTFl4A` should have CamelCase name, e.g. `FooOsRcTfl4a` (non_camel_case_types)

### ISSUE THREAD

**Issue by v0x0g** [rodrimati1992/const_format_crates#58]
I'm running into an issue where I keep getting spurious warnings like this, when I use the `assertcp!()` macro:
```rust
const_format::assertcp!(BACKENDS.len() > 0, "compiled without any backend flags enabled");
// ^ Enum `__Foo_osRcTFl4A` should have CamelCase name, e.g. `FooOsRcTfl4a` (non_camel_case_types)
```

I have attempted to add `#[allow(non_camel_case_types)]`, but since this gets applied to the macro invocation not expansion it seems to have no effect. Looking at the source, you seem to be using some very weird names in places, which is causing the warnings.

Is there any way to fix this?

**Comment by rodrimati1992** [comment]
I haven't been able to replicate this warning, what do you have in your Cargo.toml for depending on `const_format`?

**Comment by v0x0g** [comment]
> What do you have in your Cargo.toml for depending on `const_format`?

```yaml
const_format = { version = "0.2.32", features = ["assertcp"] }
```


> What Rust version are you using?

`cargo 1.80.1 (376290515 2024-07-16)`

> Aside: your specific assert doesn't need to use `const_format`, because it does no formatting, you can write it with only the standard library:

Yeah I'm aware of that, but I find `const_format` looks a bit cleaner :) Thanks for the tip though!


Funnily enough, the error seems to be showing up in my editor but not in `cargo build`.
![image](https://github.com/user-attachments/assets/8108d395-4dd4-453c-85e3-79d347d442fe)
![image](https://github.com/user-attachments/assets/a88933eb-acbc-4ca7-af68-d3705c4769f5)

**Comment by rodrimati1992** [comment]
I changed the expansion of the assert macro in the 0.2.33 release just this hour, there's hopefully no other style warning(I couldn't find any other non-standard name).

**Comment by v0x0g** [comment]
That seems to have fixed it, thanks!
